sonar.projectKey=lucaspalharesbarbosa_curriculo-online-backend
sonar.organization=lucaspalharesbarbosa
sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/rag_index.json
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
